In [88]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [42]:
dataset_path = '../../datasets/synergy-kitchen-mites-features/'
df = pd.read_pickle(dataset_path + '128.237.246.127.p')
df_labels = pd.DataFrame.from_csv(dataset_path + 'activity_labels.csv')

In [43]:
df = df.filter(regex=("ACCEL_sst_*"))

In [216]:
# train test split
indexes = df_labels.index.tolist()
np.random.shuffle(indexes)
split = round(0.7*len(indexes))
training_i = indexes[:split]
testing_i = indexes[split:]

X_train = df.loc[df.index.isin(training_i)]
X_test = df.loc[df.index.isin(testing_i)]

y_train = df_labels.loc[df_labels.index.isin(training_i)]
y_test = df_labels.loc[df_labels.index.isin(testing_i)]
y_train = y_train['label']
y_test = y_test['label']

In [217]:
ppl = Pipeline([
    ('impute', Imputer()),
    ('scale', StandardScaler()),
    ('clf', svm.SVC(kernel='linear', decision_function_shape='ovr'))
#     ('clf', LogisticRegression())
])

ppl.fit(X_train, y_train)
y_pred = ppl.predict(X_test)

In [218]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[10  0  0  1  0  0]
 [ 1 10  1  2  0  2]
 [ 0  0 12  3  0  2]
 [ 2  0  2  7  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0 15]]
0.8
