In [120]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [304]:
dataset_path = '../../datasets/synergy-kitchen-mites-features/'

source = '128.237.253.157'
target = '128.237.242.0'

df_train = pd.read_pickle(dataset_path + source + '.p')
df_test = pd.read_pickle(dataset_path + target + '.p')
df_labels = pd.DataFrame.from_csv(dataset_path + 'activity_labels.csv')

In [305]:
df_train = df_train.filter(regex=("ACCEL_sst_*"))
df_test = df_test.filter(regex=("ACCEL_sst_*"))

In [335]:
# train test split
indexes = df_labels.index.tolist()
np.random.shuffle(indexes)
split = round(0.7*len(indexes))
training_i = indexes[:split]
testing_i = indexes[split:]

X_train = df_train.loc[df_train.index.isin(training_i)]
X_test = df_test.loc[df_test.index.isin(testing_i)]

y_train = df_labels.loc[df_labels.index.isin(training_i)]
y_test = df_labels.loc[df_labels.index.isin(testing_i)]
y_train = y_train['label']
y_test = y_test['label']

X_train = X_train.reindex_axis(sorted(X_train.columns), axis=1)
X_test = X_test.reindex_axis(sorted(X_test.columns), axis=1)

In [336]:
ppl = Pipeline([
    ('impute', Imputer()),
    ('scale', StandardScaler()),
#     ('clf', svm.LinearSVC())
#     ('clf', svm.SVC(kernel='rbf', decision_function_shape='ovr'))
    ('clf', LogisticRegression())
])

ppl.fit(X_train, y_train)
y_pred = ppl.predict(X_test)

In [337]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0  0 10  0  0  0]
 [ 0  1  5  0  6  0]
 [ 0  0 19  0  0  0]
 [ 0  0 11  0  0  0]
 [ 0  0  0  0  7  0]
 [ 0  1 20  0  0  0]]
0.3375
